### ISSUE TITLE
please add the feature for a custom favorites list in the python script

### ISSUE THREAD

**Issue by merrychrishna** [evoactivity/PlutoIPTV#18]
is this the issues section for this? https://github.com/zang74/PlutoIPTV-for-TVH

i would like a feature for adding a custom favorites list added to this project https://github.com/zang74/PlutoIPTV-for-TVH 
similar to this project https://github.com/evoactivity/PlutoIPTV.

currently this project https://github.com/evoactivity/PlutoIPTV only pulls 8 hours of epg even though i have edited the script to be 48 hours. so that is why i need to use this python project https://github.com/zang74/PlutoIPTV-for-TVH but it has no favorites list

**Comment by evoactivity** [comment]
Oh it looks like you're actually trying to communicate with @zang74
I do not maintain the python version, it looks like they forked this repo as inspiration only and have since replaced it with their own implementation.

I've just tested getting 48 hours of epg, I'm going to make a release on npm. Will that solve your issue?

**Comment by merrychrishna** [comment]
yeah that will be great if you can get 48 hours working on npm. thanks so much. could you leave instructions on what command i have to run to get it working? npx pluto-iptv was only pulling 6-8hours when i tried last night. i will try again right now.

**Comment by merrychrishna** [comment]
its still only pulling 6 hours. what should i delete to start fresh?

**Comment by merrychrishna** [comment]
i have now deleted my previous files and ran it from npx again. now the epg goes up to 12 hours which is very cool. but how can i make it pull 48 hours?

**Comment by evoactivity** [comment]
That will probably be the limit from pluto itself, the time span asked for 48 hours but pluto only gives a maximum of 12 hours.

I can look at making the script loop through 12 hour chunks of time. I might get some time in the next few weeks to revisit this script. I'll @ you if I have an update.
