### ISSUE TITLE
How to make favourites

### ISSUE THREAD

**Issue by bozzio83** [evoactivity/PlutoIPTV#32]
Where do I make the pluto-favorites file?

**Comment by evoactivity** [comment]
In the folder in which the command is run.

**Comment by bozzio83** [comment]
Sorry, is there a list of channel names somewhere?

**Comment by evoactivity** [comment]
I'm not sure, they're also likely to change based on your location and from pluto making changes. Best to pull down everything then make your favourites based on the m3u you first generated.
