### ISSUE TITLE
No channel download if not in a supported country... (not an issue, but tip)

### ISSUE THREAD

**Issue by myhobby2** [evoactivity/PlutoIPTV#5]
Just for everybody also interesting in using this great tool. I was able to run this on a raspberry PI but my files were empty. Considering my location, I created an openvpn tunnel to the US and that solved my issue. 

Still wondering moving around in the US gives me additional channels... No clue yet. 

Thanks anyway for this util!

**Comment by ReenigneArcher** [comment]
@myhobby2 channels won't change within the US. One thing to note is Pluto only provides a few hours of EPG and they turn channels on and off throughout the day... especially channels in the live sports section.

**Comment by jesusvito** [comment]
Hello everyone! I do not intend to bother you... I just can't find any available PlutoTV m3u playlist(s) with latin american (mexican) content (channels)... I have no clue how could i ever get them in order for me to see them on any iptv app.

I've found this "all region" playlist but lacks LATAM (latin american channels)
PlutoTV: https://i.mjh.nz/PlutoTV/all.m3u8

Thank you !
