### ISSUE TITLE
PlutoTV Latin America

### ISSUE THREAD

**Issue by jesusvito** [evoactivity/PlutoIPTV#6]
Hello everyone! I do not intend to bother you... I just can't find any available PlutoTV m3u playlist(s) with latin american (mexican) content (channels)... I have no clue how could i ever get them in order for me to see them on any iptv app.

I've found this "all region" playlist but lacks LATAM (latin american channels)
PlutoTV: https://i.mjh.nz/PlutoTV/all.m3u8

Thank you !

**Comment by evoactivity** [comment]
If you run this script it will generate what you need, assuming you are based in latin america.

**Comment by jesusvito** [comment]
Thank you! I am in latin america... But have no idea how to run your script or use your tools :( thats why... Thank you so much anyway!
