### ISSUE TITLE
only grabs 8 hours

### ISSUE THREAD

**Issue by geosone** [evoactivity/PlutoIPTV#8]
tried to change it to grab 24 hours but its not working.

waht needs to be changed so it grabs 24 hours so that it can be added to a daily cron (nextpvr only grabs once a day the epg's)

**Comment by phillipgreenii** [comment]
I just tried this and it seemed that changing the `8` to `24` in line
```javascript
moment().add(8, 'hours').format('YYYY-MM-DD HH:00:00.000ZZ')
```
worked.  If you had run it before you changed the value, it is possible that the cache was there?  Try deleting `cache.json`.  Lastly, it is possible that now all channels have 24 hours of programming scheduled.

**Comment by merrychrishna** [comment]
i tried all that but im still only getting 8 hours. mine is set to 48 hours and have deleted the cache.json

**Comment by evoactivity** [comment]
@merrychrishna I assume you were still running the `npx pluto-iptv` command instead of `node index.js`?
I've pushed a new release so running through npx will grab 48 hours of epg.

**Comment by merrychrishna** [comment]
yes i use the command "npx pluto-iptv" and i have a bash script that runs it every 3 hours but npx pluto-iptv  is only pulling 6 - 8 hours of epg at a time still even with your 48 hour setting
